# Build Stage
FROM node:24-alpine as build-stage

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# Argument to pass VITE variables at build time
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Production Stage
FROM nginx:alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
