# Build Stage
FROM node:24-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Production Stage
FROM node:24-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist
# If you have other assets to copy, do it here (e.g. public folder, swagger docs etc)
COPY --from=builder /app/pixie-api.yaml ./

EXPOSE 3000
CMD ["npm", "start"]
